[package]
name = "typestate-automata"
version = "0.2.0"
authors = ["Jos√© Duarte <jmg.duarte@campus.fct.unl.pt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
dot = []

[dependencies]